"use client";
import { Award, BarChart3, BookOpen, CheckCircle2, ChevronRight, Flame, LogIn, Settings, ShieldCheck, Target, Trophy } from "lucide-react";
import type { AppProgress } from "@/types";
import { Button, Card, ProgressBar } from "@/components/ui";
const week=[{d:"Mo",v:24},{d:"Di",v:42},{d:"Mi",v:28},{d:"Do",v:68},{d:"Fr",v:46},{d:"Sa",v:15},{d:"So",v:0}];

export function ProgressPage({ progress }: { progress:AppProgress }) {
 const accuracy=Math.round(progress.correctAnswers/progress.totalAnswers*100);
 return <div className="page"><div className="page-intro"><div><p className="quiet-label">Dein Überblick</p><h1>Fortschritt</h1><p>Was du verstanden hast – und was als Nächstes sinnvoll ist.</p></div><select aria-label="Zeitraum"><option>Letzte 7 Tage</option><option>Letzte 30 Tage</option></select></div>
 <div className="stat-grid">{[["Lernzeit","2 h 48 min",BookOpen],["Lektionen","18",CheckCircle2],["Richtige Antworten",`${accuracy} %`,Target],["Gesammelte XP",progress.xp.toLocaleString("de-DE"),Award]].map(([label,value,Icon])=><Card key={label as string}><Icon size={20}/><b>{value as string}</b><span>{label as string}</span></Card>)}</div>
 <Card className="chart-card"><div className="card-title"><BarChart3 size={20}/><div><h2>Lernzeit</h2><p>Insgesamt 168 Minuten diese Woche</p></div></div><div className="bar-chart">{week.map((day,i)=><div key={day.d}><div className={i===4?"bar active":"bar"} style={{height:`${Math.max(day.v,4)}%`}}><span>{day.v?`${day.v} Min.`:""}</span></div><small>{day.d}</small></div>)}</div></Card>
 <div className="progress-lower"><Card><div className="card-title"><Trophy size={20}/><h2>Deine Stärken</h2></div>{[["Mathematik",82],["Englisch",74],["Deutsch",61]].map(([name,value])=><div className="strength" key={name as string}><div><b>{name as string}</b><span>{value as number}%</span></div><ProgressBar value={value as number}/></div>)}</Card><Card><div className="card-title"><Flame size={20}/><h2>Dranbleiben</h2></div><div className="streak-large"><b>{progress.streak}</b><span>Tage in Folge</span></div><p>Du hast an 5 von 7 Tagen gelernt. Das ist ein guter Rhythmus.</p><div className="weekday-row">{"MDMDFSS".split("").map((x,i)=><span className={i<5?"done":""} key={i}>{i<5?<CheckCircle2 size={16}/>:x}</span>)}</div></Card></div></div>;
}

export function ProfilePage({ progress, toggleDark, dark }: { progress:AppProgress; toggleDark:()=>void; dark:boolean }) {
 const note=(message:string)=>window.alert(message);
 return <div className="page profile-page"><section className="profile-head"><div className="profile-avatar">E</div><div><h1>Eymen</h1><p>@eymen · Klasse {progress.grade}</p><span><ShieldCheck size={15}/>Privates Profil</span></div><Button variant="secondary" onClick={()=>note("Die Profilbearbeitung wird mit deinem Konto freigeschaltet.")}>Profil bearbeiten</Button></section>
 <div className="profile-stats"><span><b>{progress.xp.toLocaleString("de-DE")}</b><small>XP</small></span><span><b>{progress.streak}</b><small>Tage Streak</small></span><span><b>18</b><small>Lektionen</small></span></div>
 <Card className="account-save"><div><LogIn size={22}/><span><b>Fortschritt dauerhaft sichern</b><small>Erstelle ein Konto, um auf allen Geräten weiterzulernen.</small></span></div><Button onClick={()=>note("Die Kontoerstellung ist für Neon Auth vorbereitet.")}>Konto erstellen</Button></Card>
 <div className="profile-columns"><Card><h2>Dein Lernziel</h2><div className="daily-goal"><Target size={23}/><div><b>{progress.dailyGoal} Minuten täglich</b><ProgressBar value={progress.minutesToday/progress.dailyGoal*100} label={`${progress.minutesToday} von ${progress.dailyGoal} Minuten heute`}/></div></div><button className="settings-row" onClick={()=>note("Deine Lernpfade findest du im Bereich Lernen.")}><span><BookOpen size={19}/>Meine Lernpfade</span><ChevronRight size={18}/></button><button className="settings-row" onClick={()=>note("Erfolge: Erste Schritte und Eine Woche dabei.")}><span><Award size={19}/>Meine Erfolge</span><ChevronRight size={18}/></button></Card>
 <Card><h2>Einstellungen</h2><button className="settings-row" onClick={toggleDark}><span><Settings size={19}/>Darstellung</span><small>{dark?"Dunkel":"Hell"}</small></button><button className="settings-row" onClick={()=>note("Dein Profil ist privat und der Demo-Fortschritt bleibt lokal.")}><span><ShieldCheck size={19}/>Datenschutz</span><small>Privat</small></button><button className="settings-row" onClick={()=>note("Lernerinnerung: täglich um 18:00 Uhr.")}><span><Flame size={19}/>Lernerinnerungen</span><small>18:00</small></button></Card></div></div>;
}
