"use client";
import { ArrowRight, BookOpen, Clock3, Flame, RotateCcw, Sparkles, Target } from "lucide-react";
import { paths, subjects } from "@/data/demo";
import type { AppProgress } from "@/types";
import { Button, Card, ProgressBar, SectionHeading } from "@/components/ui";
export function Dashboard({ progress, navigate, startLesson }: { progress:AppProgress; navigate:(p:string)=>void; startLesson:()=>void }) {
 const chosen=subjects.filter(s=>progress.selectedSubjects.includes(s.id));
 return <div className="page dashboard"><div className="page-intro"><div><p className="quiet-label">Freitag, 2. Oktober</p><h1>Guten Nachmittag, Eymen <span>👋</span></h1><p>Bereit für eine kurze Lerneinheit?</p></div><Button onClick={startLesson}><BookOpen size={18}/>Jetzt lernen</Button></div>
  <div className="dashboard-grid"><Card className="continue-card"><div className="continue-copy"><div><span className="subject-dot">Mathematik</span><h2>Brüche verstehen</h2><p>Als Nächstes: Brüche erweitern und kürzen</p></div><div className="continue-bottom"><div><span>Level 3 von 5</span><b>65 %</b></div><ProgressBar value={65}/><Button onClick={startLesson}>Weiterlernen <ArrowRight size={18}/></Button></div></div><div className="fraction-art" aria-hidden="true"><div className="fraction-circle"><i/><i/><i/><i/></div><div className="math-note">3<span/>4</div></div></Card>
   <Card className="today-card"><div className="card-title"><Target size={20}/><h2>Heute</h2></div><div className="goal-ring" style={{"--progress":"80%"} as React.CSSProperties}><div><b>{progress.minutesToday}</b><span>von {progress.dailyGoal} Min.</span></div></div><div className="today-stats"><span><Sparkles size={17}/><b>45</b><small>XP heute</small></span><span><Flame size={17}/><b>{progress.streak}</b><small>Tage</small></span></div></Card>
  </div>
  <SectionHeading title="Meine Fächer" action="Alle Fächer" onAction={()=>navigate("learn")}/><div className="subject-row">{chosen.map((s,i)=><button className="subject-card" style={{"--subject":s.color,"--soft":s.soft} as React.CSSProperties} key={s.id} onClick={()=>navigate("learn")}><span className="subject-icon">{s.icon}</span><span><b>{s.name}</b><small>{i===0?"3 aktive Themen":i===1?"1 aktives Thema":"2 aktive Themen"}</small></span><ArrowRight size={18}/></button>)}</div>
  <div className="home-lower"><Card className="challenge-card"><div className="challenge-icon"><Target size={23}/></div><div><span className="quiet-label">Tagesaufgabe</span><h3>10 Fragen richtig beantworten</h3><ProgressBar value={70} label="7 von 10 geschafft"/></div><span className="reward">+50 XP</span></Card><Card className="review-card"><div className="card-title"><RotateCcw size={20}/><h2>Wiederholen</h2></div><p>Drei Themen sind bereit für eine kurze Auffrischung.</p>{["Zähler und Nenner","Englische Präpositionen","Satzglieder"].map((x,i)=><button key={x} onClick={startLesson}><span className="review-index">{i+1}</span>{x}<Clock3 size={15}/></button>)}</Card></div>
 </div>;
}
