"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3, LockKeyhole, Play } from "lucide-react";
import { paths, subjects } from "@/data/demo";
import type { LearningPath } from "@/types";
import { Button, Card, Pill, ProgressBar, SectionHeading } from "@/components/ui";
function PathCard({ path, open }: { path:LearningPath; open:()=>void }) { const subject=subjects.find(s=>s.id===path.subjectId)!; return <button className="path-card" onClick={open}><div className="path-cover" style={{"--subject":subject.color,"--soft":subject.soft} as React.CSSProperties}><span>{subject.icon}</span><small>{subject.name}</small></div><div className="path-body"><div><Pill>{path.difficulty}</Pill><span>Klasse {path.gradeMin}–{path.gradeMax}</span></div><h3>{path.title}</h3><p>{path.description}</p><footer><span><Clock3 size={15}/>{path.minutes} Min.</span><span>{path.levels.length} Level</span></footer>{path.progress>0&&<ProgressBar value={path.progress} label={`${path.progress} % gelernt`}/>}</div></button>; }
export function LearnPage({ navigate, openPath }: { navigate:(p:string)=>void; openPath:(id:string)=>void }) { return <div className="page"><div className="page-intro"><div><p className="quiet-label">Deine Lernzentrale</p><h1>Lernen</h1><p>Setze einen Lernpfad fort oder starte etwas Neues.</p></div></div><SectionHeading title="Aktive Lernpfade"/><div className="path-grid">{paths.slice(0,3).map(p=><PathCard key={p.id} path={p} open={()=>openPath(p.id)}/>)}</div><SectionHeading title="Deine Fächer"/><div className="subject-list">{subjects.slice(0,6).map(s=><button key={s.id} style={{"--subject":s.color,"--soft":s.soft} as React.CSSProperties} onClick={()=>navigate("discover")}><span>{s.icon}</span><b>{s.name}</b><small>{paths.filter(p=>p.subjectId===s.id).length || 3} Lernpfade</small><ArrowRight size={18}/></button>)}</div></div>; }
export function PathDetail({ path, back, start }: { path:LearningPath; back:()=>void; start:(lessonId:string)=>void }) { const subject=subjects.find(s=>s.id===path.subjectId)!; let lessonCount=0; return <div className="page path-detail"><button className="back-button" onClick={back}><ArrowLeft size={18}/>Zurück zu Lernen</button><section className="path-hero" style={{"--subject":subject.color,"--soft":subject.soft} as React.CSSProperties}><div className="path-hero-copy"><Pill tone="violet">{subject.name}</Pill><h1>{path.title}</h1><p>{path.description}</p><div className="path-meta"><span><Clock3 size={17}/>{path.minutes} Minuten</span><span><BookOpen size={17}/>{path.levels.length} Level</span><span>✦ {path.xp} XP</span></div><ProgressBar value={path.progress} label={`${path.progress} % abgeschlossen`}/><Button onClick={()=>start(path.levels[0].lessons[0].id)}><Play size={17} fill="currentColor"/>Weiterlernen</Button></div><div className="path-symbol">{subject.icon}</div></section><div className="level-list">{path.levels.map((level,levelIndex)=><section className="level" key={level.id}><div className="level-heading"><span>{levelIndex+1}</span><div><h2>{level.title}</h2><p>{level.description}</p></div></div><div className="lesson-list">{level.lessons.map((lesson)=>{lessonCount++; const locked=levelIndex>2; const complete=lessonCount<3; return <button disabled={locked} onClick={()=>start(lesson.id)} className={complete?"lesson-row complete":"lesson-row"} key={lesson.id}><span className="lesson-status">{locked?<LockKeyhole size={17}/>:complete?<Check size={17}/>:<Play size={15} fill="currentColor"/>}</span><span><b>{lesson.title}</b><small>{lesson.type} · {lesson.duration} Min.</small></span><span className="lesson-xp">+{lesson.exercises.reduce((sum,x)=>sum+x.xp,0)} XP</span></button>})}</div></section>)}</div></div>; }
export function DiscoverPage({ openPath }: { openPath:(id:string)=>void }) { const [filter,setFilter]=useState("Alle Fächer"); const filtered=filter==="Klasse 6"?paths.filter(p=>p.gradeMin<=6&&p.gradeMax>=6):filter==="Bis 45 Minuten"?paths.filter(p=>p.minutes<=45):filter==="Leicht"?paths.filter(p=>p.difficulty==="Leicht"):paths; return <div className="page"><div className="page-intro"><div><p className="quiet-label">Neues entdecken</p><h1>Was möchtest du verstehen?</h1><p>Ausgewählte Lernpfade für deinen Schulalltag.</p></div></div><div className="filter-row">{["Alle Fächer","Klasse 6","Bis 45 Minuten","Leicht"].map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="featured-path"><div><Pill tone="gold">Empfohlen für dich</Pill><h2>Brüche verstehen</h2><p>Ein ruhiger Einstieg mit Bildern, kurzen Übungen und direktem Feedback.</p><Button onClick={()=>openPath("fractions")}>Lernpfad ansehen<ArrowRight size={17}/></Button></div><div className="fraction-stack"><span>½</span><span>¾</span><span>⅜</span></div></div><SectionHeading title={filter}/><div className="path-grid">{filtered.map(p=><PathCard key={p.id} path={p} open={()=>openPath(p.id)}/>)}</div></div>; }
