"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Search, X } from "lucide-react";
import { AppShell } from "./app-shell";
import { Onboarding } from "@/features/onboarding";
import { Dashboard } from "@/features/dashboard";
import { DiscoverPage, LearnPage, PathDetail } from "@/features/learning";
import { LessonPlayer } from "@/features/lesson-player";
import { ProfilePage, ProgressPage } from "@/features/progress-profile";
import { paths, subjects } from "@/data/demo";
import { progressStore } from "@/lib/storage";
import type { AppProgress, Grade, SubjectId } from "@/types";
export function StudylingApp() {
 const [ready,setReady]=useState(false); const [progress,setProgress]=useState<AppProgress|null>(null); const [page,setPage]=useState("home"); const [pathId,setPathId]=useState<string>(); const [lessonId,setLessonId]=useState<string>(); const [search,setSearch]=useState(false); const [query,setQuery]=useState(""); const [dark,setDark]=useState(false); const [toast,setToast]=useState("");
 useEffect(()=>{ const saved=progressStore.load(); setProgress(saved); setDark(localStorage.getItem("studyling-theme")==="dark"); setReady(true); if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>undefined); },[]);
 useEffect(()=>{ const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearch(true)}if(event.key==="Escape")setSearch(false)}; addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
 const update=(next:AppProgress)=>{setProgress(next);progressStore.save(next)}; const navigate=(next:string)=>{setPage(next);setPathId(undefined);scrollTo({top:0,behavior:"smooth"})};
 const finish=(grade:Grade, selected:SubjectId[], dailyGoal:number)=>progress&&update({...progress,grade,selectedSubjects:selected,dailyGoal,onboardingDone:true});
 const startLesson=(id="fractions-1-quiz")=>setLessonId(id); const completeLesson=(xp:number)=>{if(progress){const next={...progress,xp:progress.xp+xp,minutesToday:Math.min(progress.dailyGoal,progress.minutesToday+5),completedLessons:[...new Set([...progress.completedLessons,lessonId!])],correctAnswers:progress.correctAnswers+3,totalAnswers:progress.totalAnswers+4};update(next)}setLessonId(undefined);setToast(`Lektion geschafft · +${xp} XP`);setTimeout(()=>setToast(""),3200)};
 const results=useMemo(()=>{const q=query.toLowerCase();if(!q)return [];return [...paths.filter(p=>`${p.title} ${subjects.find(s=>s.id===p.subjectId)?.name}`.toLowerCase().includes(q)).map(p=>({id:p.id,title:p.title,meta:`${subjects.find(s=>s.id===p.subjectId)?.name} · Lernpfad`,kind:"path"})),...subjects.filter(s=>s.name.toLowerCase().includes(q)).map(s=>({id:s.id,title:s.name,meta:"Fach",kind:"subject"}))]},[query]);
 if(!ready||!progress)return <div className="app-loader"><span className="brand-mark">S</span></div>; if(!progress.onboardingDone)return <Onboarding finish={finish}/>; if(lessonId)return <LessonPlayer lessonId={lessonId} close={()=>setLessonId(undefined)} complete={completeLesson}/>;
 const content=pathId?<PathDetail path={paths.find(p=>p.id===pathId)??paths[0]} back={()=>setPathId(undefined)} start={startLesson}/>:page==="home"?<Dashboard progress={progress} navigate={navigate} startLesson={()=>startLesson()}/>:page==="learn"?<LearnPage navigate={navigate} openPath={setPathId}/>:page==="discover"?<DiscoverPage openPath={setPathId}/>:page==="progress"?<ProgressPage progress={progress}/>:<ProfilePage progress={progress} dark={dark} toggleDark={()=>{const n=!dark;setDark(n);localStorage.setItem("studyling-theme",n?"dark":"light")}}/>;
 return <><AppShell page={page} navigate={navigate} dark={dark} toggleDark={()=>{const n=!dark;setDark(n);localStorage.setItem("studyling-theme",n?"dark":"light")}} onSearch={()=>setSearch(true)}>{content}</AppShell>{search&&<div className="modal-layer" onMouseDown={()=>setSearch(false)}><div className="search-modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Studyling durchsuchen"><div className="search-box"><Search size={21}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Wonach möchtest du lernen?"/><button onClick={()=>setSearch(false)} aria-label="Suche schließen"><X size={20}/></button></div>{query?<div className="search-results">{results.length?results.map(r=><button key={r.kind+r.id} onClick={()=>{if(r.kind==="path")setPathId(r.id);else setPage("learn");setSearch(false);setQuery("")}}><span>{r.kind==="path"?"↗":"#"}</span><div><b>{r.title}</b><small>{r.meta}</small></div></button>):<div className="no-results"><b>Nichts gefunden</b><span>Versuche einen anderen Begriff, zum Beispiel „Brüche“.</span></div>}</div>:<div className="search-suggestions"><span>Beliebte Suchen</span>{["Brüche verstehen","Grammatik Grundlagen","Prepositions Basics"].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div>}</div></div>}{toast&&<div className="toast"><CheckCircle2 size={20}/>{toast}</div>}</>;
}
